# Generated by Django 3.0.2 on 2021-07-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_drill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_template', models.TextField(verbose_name='問題テンプレート')),
            ],
        ),
    ]
