# Generated by Django 3.0.2 on 2021-07-20 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_drill', '0002_questiontemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicDrill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField(default=False, verbose_name='正解かどうか')),
                ('question_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_drill.QuestionTemplate')),
            ],
        ),
    ]
