version: '3.7'

services:
    # サービス名は自由に設定
    django:
        # appディレクトリの中から`Dockerfile`を探す
        build: ./app
        container_name: sns_django
        # サービス起動後に入力されるコマンドを設定
        # buildで指定したDockerfileの位置がカレントディレクトリになるので注意
        command: gunicorn sns_project.wsgi:application --bind 0.0.0.0:8000
        # データを永続化させる場合の設定。`host:container`でパスを記載
        volumes:
            - ./app/:/usr/src/app/ #開発用のマウント.
            - static_volume:/usr/src/app/staticfiles
        expose:
            - 8000
        env_file: .env
        depends_on: 
            - postgres

    postgres:
        image: postgres:11.4-alpine
        container_name: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data
        env_file: .env.db

    nginx:
        build: ./nginx
        container_name: nginx
        ports:
            - 1337:80
        volumes: 
            - static_volume:/usr/src/app/staticfiles
        depends_on: 
            - django

# トップレベルに書く「名前付きvolumes」は複数サービスから参照できる
volumes:
    postgres_data:
    static_volume: