# Generated by Django 3.0.2 on 2021-01-06 03:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_num', models.CharField(max_length=10, unique=True, verbose_name='ポート番号')),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('exe', models.TextField(verbose_name='実行手順')),
                ('port_num', models.ManyToManyField(to='contents.Port', verbose_name='タグ')),
            ],
        ),
    ]
