# Generated by Django 3.0.2 on 2021-07-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_container_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='port_num',
            field=models.ManyToManyField(to='contents.Port', verbose_name='ポート番号'),
        ),
    ]
